### ISSUE TITLE
[Bug]  Incorrect or missing password.

### ISSUE THREAD

**Issue by raul-sandoval** [creativetimofficial/ct-impact-design-system-pro#18]
### Version
1.1.1
### Reproduction link
https://github.com/creativetimofficial/ct-impact-design-system-pro
### Operating System
Windows 10
### Device
Laptop Lenovo
### Browser & Version
Chrome Versión 101.0.4951.67
### Steps to reproduce
Follow the readme instruction
1.- run "npm install gulp-cli -g"
2.- run "npm install"

### What is expected?
install node folder and modules, then build with gulp
### What is actually happening?
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

---

**Comment by blackguywhocodes** [comment]
try node version 10.16.3

**Comment by raul-sandoval** [comment]
Thanks works now
