### ISSUE TITLE
[Bug] 3rd party software included in download

### ISSUE THREAD

**Issue by smaddock** [creativetimofficial/ct-impact-design-system-pro#6]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/impact-design-system-pro/
### Operating System
n/a
### Device
n/a
### Browser & Version
n/a
### Steps to reproduce
n/a
### What is expected?
All dependencies are managed through NPM, including Bootstrap, to keep repos as lean as possible.
### What is actually happening?
Just looking at the Dashboard directory:
/src/dashboard/assets/vendor/
/src/dashboard/assets/js/vendor/
/src/dashboard/assets/js/components/vendor/
/src/dashboard/scss/bootstrap/
all contain third-party software directly, outside of /node_modules/ directory that downloads when running NPM.

---
### Solution
Update all references, normalize all of the dependencies, and bring them exclusively through NPM.
### Additional comments
Zoltán at Themesburg said an update addressing this would be ready by next week; submitting here as well for completeness.

**Comment by zoltanszogyenyi** [comment]
Thanks @smaddock for pointing this out. As discussed in the email, I believe all third party dependencies from the dashboard folder as well will be kept through the NPM manager.

**Comment by zoltanszogyenyi** [comment]
@smaddock Tomorrow the update will be live.

**Comment by zoltanszogyenyi** [comment]
Update: due to a complication with the libraries the update will be postponed for tomorrow.

**Comment by zoltanszogyenyi** [comment]
Except for about 4 libraries, all of them have been transferred to NPM in version 1.1.
